// src/pages/privacy-policy/index.tsx
import Seo from "@components/seo";

import styles from "./privacy.module.scss";

function LicensePage() {
  return (
    <>
      <Seo
        title="Privacy Policy"
        href="/privacy-policy"
        description="Privacy policy for using Somraj Saha's personal website"
        imageHref="/assets/logo-og.svg"
        imageAlt="Logo for personal website."
      />

      <article className={styles.container}>
        <h1>Privacy Policy</h1>

        <p>
          While developing & maintaining this project, our reader&apos;s privacy
          concerns is of utmost importance to us. Hence, at each & every step of
          developing this website, we ensured everything is covered under the{" "}
          <a
            href="https://gdpr-info.eu"
            target="_blank"
            rel="noopener noreferrer"
          >
            GDPR
          </a>{" "}
          guidelines. That said, if you concerned about what sort of private
          data do we collect, this section of the website contains everything
          you will need to read about.
        </p>

        <h2>Information We Collect</h2>

        <ul>
          <li>
            <strong>Contact Information</strong>: We might collect your name,
            email, mobile number, phone number, street, city, state, pincode,
            country and IP address.
          </li>
          <li>
            <strong>Information You Share</strong>: We collect information &
            other details like email you share with us through HTML forms &
            other means of gathering user feedback like onlines questionnaires
            such as those from Google Forms and/or TypeForm.
          </li>
          <li>
            <strong>Demographic Information</strong>: We may collect demographic
            information about you. These information might include your age,
            your residence, country, gender, specific preferences for content &
            so on. They are collected through use of third-party trackers like
            Google Analytics, Cloudflare Analytics & Twitter Analytics. We might
            collect this as a part of a survey also.
          </li>
          <li>
            <strong>Other Information</strong>: If you use our website, we may
            collect information about your IP address and the browser you are
            using. We might look at what site you came from, duration of time
            spent on our website, pages accessed or what site you visit when you
            leave us. We might also collect the type of mobile device you are
            using, or the version of the operating system your computer or
            device is running.
          </li>
        </ul>

        <h2>We Collect Information in Different Ways</h2>

        <ul>
          <li>
            <strong>We Collect Information Directly From You</strong>: We
            collect information directly from you when you share your email with
            us to join our private email list(s). We also collect information if
            you share a feedback or ask us a question through phone or email.
          </li>
          <li>
            <strong>We Collect Information From You Passively</strong>: We use
            tracking tools like Google Analytics, Google Webmaster, Cloudlfare
            Analytics, Twitter Analytics, browser cookies and web beacons for
            collecting information about your usage of our website.
          </li>
          <li>
            <strong>We Get Information About You From Third-Parties</strong>:
            For example, if you use an integrated social media feature on our
            websites. The third-party social media site will give us certain
            information about you. This could include your name and email
            address.
          </li>
        </ul>

        <h2>Use of Your Personal Information</h2>

        <ul>
          <li>
            <strong>We Use the Information to Contact You</strong>: We might use
            the information you provide to contact you for confirmation of a
            subscription on our website or for other promotional purposes.
          </li>
          <li>
            <strong>
              We Use the Information to Respond to Your Requests or Questions
            </strong>
            : We might use your information to confirm your registration for an
            event, a subscription, giveaways & other similar activities.
          </li>
          <li>
            <strong>
              We Use Information to Improve Our Products & Services
            </strong>
            : We might use your information to customize your experience with
            us. This could include displaying content based upon your
            preferences.
          </li>
          <li>
            <strong>
              We Use Information to Look at Site Trends & Reader Interests
            </strong>
            : We may use your information to make our website and products
            better. We may combine information we get from you with information
            about you we get from third parties.
          </li>
          <li>
            <strong>We Use Information for Security Concerns</strong>: We may
            use information to protect our company, our readers, or our
            websites.
          </li>
          <li>
            <strong>We Use Information for Marketing Purposes</strong>: We might
            send you information about special promotions or offers. We might
            also tell you about new features or products. These might be our own
            offers or products, or third-party offers or products we think you
            might find interesting. Or, for example, posts containing affiliate
            links & other sponsored posts. Do note, you will be notified of the
            nature of the posts when we send you one.
          </li>
          <li>
            <strong>
              We Use Information to Send You Transactional Communications
            </strong>
            : We might send you emails about the terms & conditions of services
            between Somraj Saha & you or a subscription.
          </li>
        </ul>

        <p>We use the information as permitted by law.</p>

        <h2>Sharing of Information with Third-Parties</h2>

        <ul>
          <li>
            <strong>
              We Will Share Information With Third Parties Who Perform Services
              On Our Behalf
            </strong>
            : We share information with vendors who help us manage our email
            list subscription process. Some vendors may be located outside of
            India.
          </li>
          <li>
            <strong>
              We Will Share Information With Our Business Partners
            </strong>
            : : We share information with vendors who help us manage our email
            list subscription process. Some vendors may be located outside of
            India.
          </li>
          <li>
            <strong>
              We Will Share Information If We Think We Have to Comply With or to
              Protect Ourselves
            </strong>
            : We will share information to respond to a court order or subpoena.
            We may also share it if a government agency or investigatory body
            requests. Or, we might also share information when we are
            investigating potential fraud.
          </li>
          <li>
            <strong>
              We May Share Information With Any Successor to All or Part of Our
              Business
            </strong>
            : For example, if part of our business is sold we may give our
            reader list as part of that transaction.
          </li>
          <li>
            <strong>
              We May Share Your Information for Reasons Not Described in This
              Policy
            </strong>
            : We will tell you before we do this along with a detailed
            explanation for us to do so.
          </li>
        </ul>

        <h2>Email Opt-Out and/or Unsubscribe from Routine Updates</h2>

        <p>
          You can opt out of receiving our marketing emails and/or receiving
          personalized contents for our private email list(s). To stop receiving
          our promotional emails, please email{" "}
          <a
            href="mailto:somraj.mle@gmail.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            somraj.mle@gmail.com
          </a>
          . It may take about ten days to process your request.
        </p>

        <p>
          But, to receive a prompt unsubsribe request, please check the last
          email you received. There will be an unsubscribe option at the bottom
          of it. Do note, even if you opt out of getting marketing messages, we
          will still be sending you transactional messages through email about
          your purchase of our goods & services.
        </p>

        <h2>Third-Party Sites</h2>

        <p>
          If you click on one of the links to third party websites, you may be
          taken to websites we do not control. This policy does not apply to the
          privacy practices of those websites. Read the privacy policy of other
          websites carefully. We are not responsible for these third party
          sites.
        </p>

        <h2>Grievance Complaints</h2>

        <p>
          In accordance with{" "}
          <a
            href="https://www.indiacode.nic.in/bitstream/123456789/1999/3/A2000-21.pdf"
            target="_blank"
            rel="noopener noreferrer"
          >
            Information Technology Act, 2000
          </a>{" "}
          and rules made there under, the name and contact details of the
          individual to share your grievance complaints at the provided email
          address.
        </p>

        {/* FIXME: Figure a way out to style the following component. */}
        {/* <address> */}
        {/*     Mr. Somraj Saha Calcutta Textiles, Santipara Masjid Road Agartala, */}
        {/*     Tripura - 799001 Phone: (+91) 7731 824 653 Email: somraj.mle@gmail.com */}
        {/* </address> */}

        <p>
          If you have any questions about this Policy or other privacy concerns,
          you can reach out to us over electronic mail, traditional mail,
          telephone or whichever means is convenient for you. Please do so
          without any hesitation.
        </p>

        <h2>Updates to This Policy</h2>

        <p>
          From time to time we may change our privacy practices. We will notify
          you of any material changes to this policy as required by law. We will
          also post an updated copy on our website which you will find on the
          top of this Privacy Policy document. Please check our site
          periodically for updates.
        </p>

        <h2>Jurisdiction</h2>

        <p>
          If you choose to visit the website, your visit and any dispute over
          privacy is subject to this Policy and the website&apos;s terms of use.
          In addition to the foregoing, any disputes arising under this Policy
          shall be governed by the laws of India.
        </p>
      </article>
    </>
  );
}

export default LicensePage;

// website/pages/privacy-policy.vue
<template>
  <article>
    <h1>Privacy Policy</h1>
    <p>
      While developing and maintaining this project, our reader&'s privacy
      concerns is of utmost importance to us. Hence, at each and every step of
      developing this website, we ensured everything is covered under the
      <a href="https://gdpr-info.eu" target="_blank"> GDPR</a> guidelines. That
      said, if you are concerned about what sort of private data do we collect,
      this section of the website contains everything you will need to read
      about.
    </p>
    <h2>Information We Collect</h2>
    <ul>
      <li>
        <strong>Contact Information</strong>: We might collect your name, email,
        mobile number, phone number, street, city, state, pincode, country and
        IP address.
      </li>
      <li>
        <strong>Information You Share</strong>: We collect information & other
        details like email you share with us through HTML forms & other means of
        gathering user feedback like onlines questionnaires such as those from
        Google Forms and/or TypeForm.
      </li>
      <li>
        <strong>Demographic Information</strong>: We may collect demographic
        information about you. These information might include your age, your
        residence, country, gender, specific preferences for content & so on.
        They are collected through use of third-party trackers like Google
        Analytics, Cloudflare Analytics & Twitter Analytics. We might collect
        this as a part of a survey also.
      </li>
      <li>
        <strong>Other Information</strong>: If you use our website, we may
        collect information about your IP address and the browser you are using.
        We might look at what site you came from, duration of time spent on our
        website, pages accessed or what site you visit when you leave us. We
        might also collect the type of mobile device you are using, or the
        version of the operating system your computer or device is running.
      </li>
    </ul>
    <h2>We Collect Information in Different Ways</h2>
    <ul>
      <li>
        <strong>We Collect Information Directly From You</strong>: We collect
        information directly from you when you share your email with us to join
        our private email list(s). We also collect information if you share a
        feedback or ask us a question through phone or email.
      </li>
      <li>
        <strong>We Collect Information From You Passively</strong>: We use
        tracking tools like Google Analytics, Google Webmaster, Cloudlfare
        Analytics, Twitter Analytics, browser cookies and web beacons for
        collecting information about your usage of our website.
      </li>
      <li>
        <strong>We Get Information About You From Third-Parties</strong>: For
        example, if you use an integrated social media feature on our websites.
        The third-party social media site will give us certain information about
        you. This could include your name and email address.
      </li>
    </ul>
    <h2>Use of Your Personal Information</h2>
    <ul>
      <li>
        <strong>We Use the Information to Contact You</strong>: We might use the
        information you provide to contact you for confirmation of a
        subscription on our website or for other promotional purposes.
      </li>
      <li>
        <strong>
          We Use the Information to Respond to Your Requests or Questions
        </strong>
        : We might use your information to confirm your registration for an
        event, a subscription, giveaways & other similar activities.
      </li>
      <li>
        <strong> We Use Information to Improve Our Products & Services</strong>
        : We might use your information to customize your experience with us.
        This could include displaying content based upon your preferences.
      </li>
      <li>
        <strong>
          We Use Information to Look at Site Trends & Reader Interests
        </strong>
        : We may use your information to make our website and products better.
        We may combine information we get from you with information about you we
        get from third parties.
      </li>
      <li>
        <strong>We Use Information for Security Concerns</strong>: We may use
        information to protect our company, our readers, or our websites.
      </li>
      <li>
        <strong>We Use Information for Marketing Purposes</strong>: We might
        send you information about special promotions or offers. We might also
        tell you about new features or products. These might be our own offers
        or products, or third-party offers or products we think you might find
        interesting. Or, for example, posts containing affiliate links & other
        sponsored posts. Do note, you will be notified of the nature of the
        posts when we send you one.
      </li>
      <li>
        <strong>
          We Use Information to Send You Transactional Communications
        </strong>
        : We might send you emails about the terms & conditions of services
        between Somraj Saha & you or a subscription.
      </li>
    </ul>
    <p>We use the information as permitted by law.</p>
    <h2>Sharing of Information with Third-Parties</h2>
    <ul>
      <li>
        <strong>
          We Will Share Information With Third Parties Who Perform Services On
          Our Behalf
        </strong>
        : We share information with vendors who help us manage our email list
        subscription process. Some vendors may be located outside of India.
      </li>
      <li>
        <strong>We Will Share Information With Our Business Partners</strong>: :
        We share information with vendors who help us manage our email list
        subscription process. Some vendors may be located outside of India.
      </li>
      <li>
        <strong>
          We Will Share Information If We Think We Have to Comply With or to
          Protect Ourselves
        </strong>
        : We will share information to respond to a court order or subpoena. We
        may also share it if a government agency or investigatory body requests.
        Or, we might also share information when we are investigating potential
        fraud.
      </li>
      <li>
        <strong>
          We May Share Information With Any Successor to All or Part of Our
          Business
        </strong>
        : For example, if part of our business is sold we may give our reader
        list as part of that transaction.
      </li>
      <li>
        <strong>
          We May Share Your Information for Reasons Not Described in This Policy
        </strong>
        : We will tell you before we do this along with a detailed explanation
        for us to do so.
      </li>
    </ul>
    <h2>Email Opt-Out and/or Unsubscribe from Routine Updates</h2>
    <p>
      You can opt out of receiving our marketing emails and/or receiving
      personalized contents for our private email list(s). To stop receiving our
      promotional emails, please email
      <a href="mailto:contact@jarmos.dev" target="_blank">
        contact@jarmos.dev
      </a>
      . It may take about ten days to process your request.
    </p>
    <p>
      But, to receive a prompt unsubsribe request, please check the last email
      you received. There will be an unsubscribe option at the bottom of it. Do
      note, even if you opt out of getting marketing messages, we will still be
      sending you transactional messages through email about your purchase of
      our goods & services.
    </p>
    <h2>Third-Party Sites</h2>
    <p>
      If you click on one of the links to third party websites, you may be taken
      to websites we do not control. This policy does not apply to the privacy
      practices of those websites. Read the privacy policy of other websites
      carefully. We are not responsible for these third party sites.
    </p>
    <h2>Grievance Complaints</h2>
    <p>
      In accordance with
      <a
        href="https://www.indiacode.nic.in/bitstream/123456789/1999/3/A2000-21.pdf"
        target="_blank"
      >
        Information Technology Act, 2000</a
      >
      and rules made there under, the name and contact details of the individual
      to share your grievance complaints at the provided email address.
    </p>
    <address>
      <div>Somraj Saha,</div>
      <div>2nd Floor, S.K. Market, Masjid Road</div>
      <div>Agartala, West Tripura,</div>
      <div>Tripura, India</div>
      <div>PIN: 799001</div>
      <div>Email: contact@jarmos.dev</div>
      <div>Phone: (+91) 7731 824 653 | (+91) 8794 891 882</div>
    </address>
    <p>
      If you have any questions about this Policy or other privacy concerns, you
      can reach out to us over electronic mail, traditional mail, telephone or
      whichever means is convenient for you. Please do so without any
      hesitation.
    </p>
    <h2>Updates to This Policy</h2>
    <p>
      From time to time we may change our privacy practices. We will notify you
      of any material changes to this policy as required by law. We will also
      post an updated copy on our website which you will find on the top of this
      Privacy Policy document. Please check our site periodically for updates.
    </p>
    <h2>Jurisdiction</h2>
    <p>
      If you choose to visit the website, your visit and any dispute over
      privacy is subject to this Policy and the website&'s terms of use. In
      addition to the foregoing, any disputes arising under this Policy shall be
      governed by the laws of India.
    </p>
  </article>
</template>

<script lang="ts" setup>
const title = "Privacy Policy";
const description = `Read the Privacy Policy of jarmos.dev. Learn how we collect, use,
and protect your personal data under GDPR, analytics tools, and Indian IT laws.`;
const image = "/icons/favicon.svg";
const baseURL = useRuntimeConfig().public.baseURL;

// Set the the title of the page
useHead({
  title: title,
});

// Set the SEO metadata for the page
useSeoMeta({
  description: description,
  ogTitle: title,
  ogDescription: description,
  ogImage: image,
  ogUrl: `${baseURL}/privacy-policy`,
  twitterTitle: title,
  twitterDescription: description,
  twitterImage: image,
  twitterCard: "summary",
});
</script>

<style lang="scss" scoped>
article {
  padding: 0 2rem;
  margin: 2rem auto;

  address {
    background-color: #1c2c35;
    padding: 1rem;

    div {
      margin: 0.35rem auto;
    }
  }

  // Tablet
  @media screen and (min-width: 768px) {
    padding: 0 4rem;
  }

  // Laptops
  @media screen and (min-width: 1024px) {
    padding: 0 7rem;
  }

  // 2K Desktops
  @media screen and (min-width: 1440px) {
    padding: 0 14rem;
  }
}
</style>
