// pages/terms-and-conditions/index.tsx
import Head from "next/head";
import Link from "next/link";

import styles from "./terms.module.scss";

function TermsAndConditionsPage() {
    return (
        <>
            <Head>
                <title>Terms & Conditions | Somraj Saha</title>
            </Head>

            <article className={styles.container}>
                <h1>Terms And Conditions</h1>
                <p>
                    <strong>
                        PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS
                        WEBSITE, SUBSRIBING TO OUR PRODUCTS AND/OR USING OUR SERVICES FROM
                        THIS WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND
                        CONDITIONS OF THIS AGREEMENT.
                    </strong>
                </p>
                <p>
                    This Terms of Service Agreement (the &quot;<strong>Agreement</strong>
                    &quot;) governs your use of this website,{" "}
                    <Link href="/">jarmos.vercel.app</Link> (the &quot;
                    <strong>Website</strong>&quot;), business name (&quot;
                    <strong>Somraj Saha</strong>&quot;) offer of services and/or products
                    for purchase and/or subscription on this Website, or your purchase of
                    products and/or subscriptions available on this Website. This
                    Agreement includes, and incorporates by this reference, the policies
                    and guidelines referenced below. Somraj Saha reserves the right to
                    change or revise the terms and conditions of this Agreement at any
                    time by posting any changes or a revised Agreement on this Website.
                    Somraj Saha will alert you that changes or revisions have been made by
                    indicating on the top of this Agreement the date it was last revised.
                    The changes or revised Agreement will be effective immediately after
                    it is posted on this Website. Your use of the Website following the
                    posting any such changes or of a revised Agreement will constitute
                    your acceptance of any such changes or revisions. Somraj Saha
                    encourages you to review this Agreement whenever you visit the Website
                    to make sure that you understand the terms and conditions governing
                    use of the Website. This Agreement does not alter in any way the terms
                    or conditions of any other written agreement you may have with Somraj
                    Saha for other products or services. If you do not agree to this
                    Agreement (including any referenced policies or guidelines), please
                    immediately terminate your use of the Website. If you would like to
                    print this Agreement, please click the print button on your browser
                    toolbar.
                </p>
                <h2>I. Products</h2>
                <p>
                    Terms of Offer. This Website offers for sale certain products (the
                    &quot;<strong>Products</strong>&quot;). By placing an order for
                    Products through this Website, you agree to the terms and conditions
                    set forth in this Agreement.
                </p>

                <p>
                    <strong>Reader Solicitation</strong>: Unless you notify Somraj Saha,
                    while they are communicating with you, of your desire to opt out from
                    further direct company communications and solicitations, you are
                    agreeing to continue to receive further emails and solicitations from
                    Somraj Saha.
                </p>

                <p>
                    <strong>Opt-Out Procedure</strong>: We provide 3 easy ways to opt out
                    of from future solicitations.
                    <ol>
                        <li>
                            You may use the opt out link found in any email solicitation that
                            you may receive.{" "}
                        </li>
                        <li>
                            You may also choose to opt out, via sending your email address to:{" "}
                            <a
                                href="mailto:somraj.mle@gmail.com."
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                somraj.mle@gmail.com
                            </a>
                        </li>
                    </ol>
                </p>
                <p>
                    <strong>Proprietary Rights</strong>. Somraj Saha has proprietary
                    rights and trade secrets in the Products & Services mentioned in this
                    Website. You may copy, reproduce, resell or redistribute any Products
                    & Services manufactured and/or distributed by Somraj Saha under the
                    Terms & Conditions of the{" "}
                    <a
                        href="https://creativecommons.org/licenses/by-nc/4.0/legalcode"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        CC BY-NA 4.0
                    </a>
                    .
                </p>
                <p>
                    <strong>Sales Tax</strong>. If you purchase any Products and/or
                    Services, you will be responsible for paying any applicable sales tax
                    (<em>if any</em>).
                </p>
                <h2>II. Website</h2>
                <p>
                    Content; Intellectual Property; Third Party Links. In addition to
                    making Products available, this Website also offers information and
                    marketing materials. This Website also offers information, both
                    directly and through indirect links to third-party websites, about
                    Information Technology (IT). Somraj Saha does not always create the
                    information offered on this Website; instead the information is often
                    gathered from other sources. To the extent that Somraj Saha does
                    create the content on this Website, such content is protected by
                    intellectual property laws of the India, foreign nations, and
                    international bodies. Unauthorized use of the material may violate
                    copyright, trademark, and/or other laws. You acknowledge that your use
                    of the content on this Website is for personal, noncommercial use. Any
                    links to third-party websites are provided solely as a convenience to
                    you. Somraj Saha does not endorse the contents on any such third-party
                    websites. Somraj Saha is not responsible for the content of or any
                    damage that may result from your access to or reliance on these
                    third-party websites. If you link to third-party websites, you do so
                    at your own risk.
                </p>
                <p>
                    Use of Website; Somraj Saha is not responsible for any damages
                    resulting from use of this website by anyone. You will not use the
                    Website for illegal purposes. You will (1) abide by all applicable
                    local, state, national, and international laws and regulations in your
                    use of the Website (including laws regarding intellectual property),
                    (2) not interfere with or disrupt the use and enjoyment of the Website
                    by other users, (3) not resell material on the Website, (4) not
                    engage, directly or indirectly, in transmission of &quot;spam&quot;,
                    chain letters, junk mail or any other type of unsolicited
                    communication, and (5) not defame, harass, abuse, or disrupt other
                    users of the Website
                </p>
                <p>
                    License. By using this Website, you are granted a limited,
                    non-exclusive, non-transferable right to use the content and materials
                    on the Website in connection with your normal, noncommercial, use of
                    the Website under the Terms & Conditions laid down by{" "}
                    <a
                        href="https://creativecommons.org/licenses/by-nc/4.0/legalcode"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        CC BY-NA 4.0
                    </a>
                    . You may copy, reproduce, transmit, distribute, or create derivative
                    works of such content or information with/without express written
                    authorization from Somraj Saha or the applicable third party (if third
                    party content is at issue).
                </p>
                <p>
                    Sharing Information. By sharing your personal information, storing, or
                    transmitting any content with us on the Website, you hereby grant
                    Somraj Saha a perpetual, worldwide, non-exclusive, royalty-free,
                    assignable, right and license to use, copy, display, perform, create
                    derivative works from, distribute, have distributed, transmit and
                    assign such content in any form, in all media now known or hereinafter
                    created, anywhere in the world. You are solely responsible for your
                    interactions with other users of the Website and any content they
                    share with you. Somraj Saha is not liable for any damage or harm
                    resulting from any posts by or interactions between users. Somraj Saha
                    reserves the right, but has no obligation, to monitor interactions
                    between and among users of the Website and to remove any content
                    Somraj Saha deems objectionable, in Somraj Saha&apos;s sole
                    discretion.
                </p>
                <h2>III. Disclaimer of Warranties</h2>
                <p>
                    YOUR USE OF THIS WEBSITE AND/OR PRODUCTS ARE AT YOUR SOLE RISK. THE
                    WEBSITE AND PRODUCTS ARE OFFERED ON AN &quot;<strong>AS IS</strong>
                    &quot; AND &quot;<strong>AS AVAILABLE</strong>&quot; BASIS. SOMRAJ
                    SAHA EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS
                    OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
                    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
                    WITH RESPECT TO THE PRODUCTS OR WEBSITE CONTENT, OR ANY RELIANCE UPON
                    OR USE OF THE WEBSITE CONTENT OR PRODUCTS. (&quot;
                    <strong>PRODUCTS&quot; INCLUDE TRIAL PRODUCTS</strong>.)
                </p>
                <p>
                    WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, SOMRAJ SAHA MAKES NO
                    WARRANTY:
                </p>
                <p>
                    NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU
                    FROM THIS WEBSITE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED
                    HEREIN.
                </p>
                <p>
                    AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PRODUCTS OR
                    THAT DEFECTS IN PRODUCTS WILL BE CORRECTED.
                </p>
                <p>REGARDING ANY PRODUCTS PURCHASED OR OBTAINED THROUGH THE WEBSITE.</p>
                <p>
                    SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES,
                    SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
                </p>
                <h2>IV. Limitation of Liability</h2>
                <p>
                    SOMRAJ SAHA ENTIRE LIABILITY, AND YOUR EXCLUSIVE REMEDY, IN LAW, IN
                    EQUITY, OR OTHWERWISE, WITH RESPECT TO THE WEBSITE CONTENT AND
                    PRODUCTS AND/OR FOR ANY BREACH OF THIS AGREEMENT IS SOLELY LIMITED TO
                    THE AMOUNT YOU PAID, LESS SHIPPING AND HANDLING, FOR PRODUCTS AND/OR
                    SERVICES PURCHASED VIA THE WEBSITE.
                </p>
                <p>
                    SOMRAJ SAHA WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
                    SPECIAL OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH THIS AGREEMENT OR
                    THE PRODUCTS IN ANY MANNER, INCLUDING LIABILITIES RESULTING FROM (1)
                    THE USE OR THE INABILITY TO USE THE WEBSITE CONTENT OR PRODUCTS; (2)
                    THE COST OF PROCURING SUBSTITUTE PRODUCTS OR CONTENT; (3) ANY PRODUCTS
                    PURCHASED OR OBTAINED OR TRANSACTIONS ENTERED INTO THROUGH THE
                    WEBSITE; OR (4) ANY LOST PROFITS YOU ALLEGE.
                </p>
                <p>
                    SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF
                    LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE ABOVE
                    LIMITATIONS MAY NOT APPLY TO YOU.
                </p>
                <h2>V. Indemnification</h2>
                <p>
                    You will release, indemnify, defend and hold harmless Somraj Saha, and
                    any of his contractors, agents, employees, officers, directors,
                    shareholders, affiliates and assigns from all liabilities, claims,
                    damages, costs and expenses, including reasonable attorneys&apos; fees
                    and expenses, of third parties relating to or arising out of (1) this
                    Agreement or the breach of your warranties, representations and
                    obligations under this Agreement; (2) the Website content or your use
                    of the Website content; (3) the Products or your use of the Products
                    (including Trial Products); (4) any intellectual property or other
                    proprietary right of any person or entity; (5) your violation of any
                    provision of this Agreement; or (6) any information or data you
                    supplied to Somraj Saha. When Somraj Saha is threatened with suit or
                    sued by a third party, Somraj Saha may seek written assurances from
                    you concerning your promise to indemnify Somraj Saha; your failure to
                    provide such assurances may be considered by Somraj Saha to be a
                    material breach of this Agreement. Somraj Saha will have the right to
                    participate in any defense by you of a third-party claim related to
                    your use of any of the Website content or Products, with counsel of
                    Somraj Saha&apos;s choice at its expense. Somraj Saha will reasonably
                    cooperate in any defense by you of a third-party claim at your request
                    and expense. You will have sole responsibility to defend Somraj Saha
                    against any claim, but you must receive Somraj Saha a prior written
                    consent regarding any related settlement. The terms of this provision
                    will survive any termination or cancellation of this Agreement or your
                    use of the Website or Products.
                </p>
                <h2>VI. Privacy</h2>
                <p>
                    Somraj Saha believes strongly in protecting user privacy and providing
                    you with notice of Somraj Saha&apos;s blog&apos;s use of data. Please
                    refer to Somraj Saha&apos;s{" "}
                    <Link href="/privacy-policy">Privacy Policy</Link>, incorporated by
                    reference herein, that is posted on the Website.
                </p>
                <h2>VII. Agreement to be Bound</h2>
                <p>
                    By using this Website, ordering Products and/or subscribing to our
                    Services, you acknowledge that you have read and agree to be bound by
                    this Agreement and all terms and conditions on this Website.
                </p>
                <h2>VIII. General</h2>
                <p>
                    Force Majeure. Somaraj Saha will not be deemed in default hereunder or
                    held responsible for any cessation, interruption or delay in the
                    performance of its obligations hereunder due to earthquake, flood,
                    fire, storm, natural disaster, act of God, war, terrorism, armed
                    conflict, labor strike, lockout, or boycott.
                </p>
                <p>
                    Cessation of Operation. Somraj Saha may at any time, in its sole
                    discretion and without advance notice to you, cease operation of the
                    Website and distribution of the Products.
                </p>
                <p>
                    Entire Agreement. This Agreement comprises the entire agreement
                    between you and Somraj Saha and supersedes any prior agreements
                    pertaining to the subject matter contained herein.
                </p>
                <p>
                    Effect of Waiver. The failure of Somraj Saha to exercise or enforce
                    any right or provision of this Agreement will not constitute a waiver
                    of such right or provision. If any provision of this Agreement is
                    found by a court of competent jurisdiction to be invalid, the parties
                    nevertheless agree that the court should endeavor to give effect to
                    the parties&apos; intentions as reflected in the provision, and the
                    other provisions of this Agreement remain in full force and effect.
                </p>
                <p>
                    Governing Law;{" "}
                    <a
                        href="https://main.sci.gov.in/jurisdiction"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Supreme Court of India
                    </a>
                    . This Website originates from the city of Agartala in Tripura, India.
                    This Agreement will be governed by the laws of the State of India
                    without regard to its conflict of law principles to the contrary.
                    Neither you nor Somraj Saha will commence or prosecute any suit,
                    proceeding or claim to enforce the provisions of this Agreement, to
                    recover damages for breach of or default of this Agreement, or
                    otherwise arising under or by reason of this Agreement, other than in
                    courts located in State of India. By using this Website or ordering
                    and/or subscribing to our Products, you consent to the jurisdiction
                    and venue of such courts in connection with any action, suit,
                    proceeding or claim arising under or by reason of this Agreement. You
                    hereby waive any right to trial by jury arising out of this Agreement
                    and any related documents.
                </p>
                <p>
                    Statute of Limitation. You agree that regardless of any statute or law
                    to the contrary, any claim or cause of action arising out of or
                    related to use of the Website or Products or this Agreement must be
                    filed within one (1) year after such claim or cause of action arose or
                    be forever barred.
                </p>
                <p>
                    Waiver of Class Action Rights. BY ENTERING INTO THIS AGREEMENT, YOU
                    HEREBY IRREVOCABLY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH
                    THOSE OF OTHER IN THE FORM OF A CLASS ACTION OR SIMILAR PROCEDURAL
                    DEVICE. ANY CLAIMS ARISING OUT OF, RELATING TO, OR CONNECTION WITH
                    THIS AGREEMENT MUST BE ASSERTED INDIVIDUALLY.
                </p>
                <p>
                    Termination. Somraj Saha reserves the right to terminate your access
                    to the Website if it reasonably believes, in its sole discretion, that
                    you have breached any of the terms and conditions of this Agreement.
                    Following termination, you will not be permitted to use the Website
                    and Somraj Saha may, in its sole discretion and without advance notice
                    to you, cancel any outstanding orders for Products. If your access to
                    the Website is terminated, Somraj Saha reserves the right to exercise
                    whatever means it deems necessary to prevent unauthorized access of
                    the Website. This Agreement will survive indefinitely unless and until
                    Somraj Saha chooses, in its sole discretion and without advance to
                    you, to terminate it.
                </p>
                <p>
                    Domestic Use. Somraj Saha makes no representation that the Website or
                    Products are appropriate or available for use in locations outside
                    India. Users who access the Website from outside India do so at their
                    own risk and initiative and must bear all responsibility for
                    compliance with any applicable local laws.
                </p>
                <p>
                    Assignment. You may not assign your rights and obligations under this
                    Agreement to anyone. Somraj Saha may assign its rights and obligations
                    under this Agreement in its sole discretion and without advance notice
                    to you.
                </p>
                <p>
                    BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE
                    TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
                </p>
            </article>
        </>
    );
}

export default TermsAndConditionsPage;

// website/pages/terms-and-conditions.vue
<template>
  <article>
    <h1>Terms and Conditions</h1>
    <p>
      <strong>
        PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS
        WEBSITE, SUBSRIBING TO OUR PRODUCTS AND/OR USING OUR SERVICES FROM THIS
        WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS
        AGREEMENT.
      </strong>
    </p>
    <p>
      This Terms of Service Agreement (the "<strong>Agreement</strong>
      ") governs your use of this website,
      <a href="/"> jarmos.dev</a>
      (the "
      <strong>Website</strong>"), business name ("
      <strong>Somraj Saha</strong>") offer of services and/or products for
      purchase and/or subscription on this Website, or your purchase of products
      and/or subscriptions available on this Website. This Agreement includes,
      and incorporates by this reference, the policies and guidelines referenced
      below. Somraj Saha reserves the right to change or revise the terms and
      conditions of this Agreement at any time by posting any changes or a
      revised Agreement on this Website. Somraj Saha will alert you that changes
      or revisions have been made by indicating on the top of this Agreement the
      date it was last revised. The changes or revised Agreement will be
      effective immediately after it is posted on this Website. Your use of the
      Website following the posting any such changes or of a revised Agreement
      will constitute your acceptance of any such changes or revisions. Somraj
      Saha encourages you to review this Agreement whenever you visit the
      Website to make sure that you understand the terms and conditions
      governing use of the Website. This Agreement does not alter in any way the
      terms or conditions of any other written agreement you may have with
      Somraj Saha for other products or services. If you do not agree to this
      Agreement (including any referenced policies or guidelines), please
      immediately terminate your use of the Website. If you would like to print
      this Agreement, please click the print button on your browser toolbar.
    </p>
    <h2>I. Products</h2>
    <p>
      Terms of Offer. This Website offers for sale certain products (the
      "<strong>Products</strong>"). By placing an order for Products through
      this Website, you agree to the terms and conditions set forth in this
      Agreement.
    </p>
    <p>
      <strong>Reader Solicitation</strong>: Unless you notify Somraj Saha, while
      they are communicating with you, of your desire to opt out from further
      direct company communications and solicitations, you are agreeing to
      continue to receive further emails and solicitations from Somraj Saha.
    </p>
    <p>
      <strong>Opt-Out Procedure</strong>: We provide 3 easy ways to opt out of
      from future solicitations.
    </p>
    <ol>
      <li>
        You may use the opt out link found in any email solicitation that you
        may receive.
      </li>
      <li>
        You may also choose to opt out, via sending your email address to:
        <a href="mailto:contact@jarmos.dev" target="_blank">
          contact@jarmos.dev
        </a>
      </li>
    </ol>
    <p>
      <strong>Proprietary Rights</strong>. Somraj Saha has proprietary rights
      and trade secrets in the Products & Services mentioned in this Website.
      You may copy, reproduce, resell or redistribute any Products & Services
      manufactured and/or distributed by Somraj Saha under the Terms &
      Conditions of the
      <a
        href="https://creativecommons.org/licenses/by-nc/4.0/legalcode"
        target="_blank"
      >
        CC BY-NA 4.0
      </a>
      .
    </p>
    <p>
      <strong>Sales Tax</strong>. If you purchase any Products and/or Services,
      you will be responsible for paying any applicable sales tax (
      <em>if any</em>).
    </p>
    <h2>II. Website</h2>
    <p>
      Content; Intellectual Property; Third Party as. In addition to making
      Products available, this Website also offers information and marketing
      materials. This Website also offers information, both directly and through
      indirect links to third-party websites, about Information Technology (IT).
      Somraj Saha does not always create the information offered on this
      Website; instead the information is often gathered from other sources. To
      the extent that Somraj Saha does create the content on this Website, such
      content is protected by intellectual property laws of the India, foreign
      nations, and international bodies. Unauthorized use of the material may
      violate copyright, trademark, and/or other laws. You acknowledge that your
      use of the content on this Website is for personal, noncommercial use. Any
      links to third-party websites are provided solely as a convenience to you.
      Somraj Saha does not endorse the contents on any such third-party
      websites. Somraj Saha is not responsible for the content of or any damage
      that may result from your access to or reliance on these third-party
      websites. If you link to third-party websites, you do so at your own risk.
    </p>
    <p>
      Use of Website; Somraj Saha is not responsible for any damages resulting
      from use of this website by anyone. You will not use the Website for
      illegal purposes. You will (1) abide by all applicable local, state,
      national, and international laws and regulations in your use of the
      Website (including laws regarding intellectual property), (2) not
      interfere with or disrupt the use and enjoyment of the Website by other
      users, (3) not resell material on the Website, (4) not engage, directly or
      indirectly, in transmission of "spam", chain letters, junk mail or any
      other type of unsolicited communication, and (5) not defame, harass,
      abuse, or disrupt other users of the Website
    </p>
    <p>
      License. By using this Website, you are granted a limited, non-exclusive,
      non-transferable right to use the content and materials on the Website in
      connection with your normal, noncommercial, use of the Website under the
      Terms & Conditions laid down by
      <a
        href="https://creativecommons.org/licenses/by-nc/4.0/legalcode"
        target="_blank"
      >
        CC BY-NA 4.0
      </a>
      . You may copy, reproduce, transmit, distribute, or create derivative
      works of such content or information with/without express written
      authorization from Somraj Saha or the applicable third party (if third
      party content is at issue).
    </p>
    <p>
      Sharing Information. By sharing your personal information, storing, or
      transmitting any content with us on the Website, you hereby grant Somraj
      Saha a perpetual, worldwide, non-exclusive, royalty-free, assignable,
      right and license to use, copy, display, perform, create derivative works
      from, distribute, have distributed, transmit and assign such content in
      any form, in all media now known or hereinafter created, anywhere in the
      world. You are solely responsible for your interactions with other users
      of the Website and any content they share with you. Somraj Saha is not
      liable for any damage or harm resulting from any posts by or interactions
      between users. Somraj Saha reserves the right, but has no obligation, to
      monitor interactions between and among users of the Website and to remove
      any content Somraj Saha deems objectionable, in Somraj Saha&apos;s sole
      discretion.
    </p>
    <h2>III. Disclaimer of Warranties</h2>
    <p>
      Somraj Saha believes strongly in protecting user privacy and providing you
      with notice of Somraj Saha&apos;s blog&apos;s use of data. Please refer to
      Somraj Saha&apos;s
      <a href="/privacy-policy"> Privacy Policy</a>
      , incorporated by reference herein, that is posted on the Website.
    </p>
    <h2>VII. Agreement to be Bound</h2>
    <p>
      By using this Website, ordering Products and/or subscribing to our
      Services, you acknowledge that you have read and agree to be bound by this
      Agreement and all terms and conditions on this Website.
    </p>
    <h2>VIII. General</h2>
    <p>
      Force Majeure. Somaraj Saha will not be deemed in default hereunder or
      held responsible for any cessation, interruption or delay in the
      performance of its obligations hereunder due to earthquake, flood, fire,
      storm, natural disaster, act of God, war, terrorism, armed conflict, labor
      strike, lockout, or boycott.
    </p>
    <p>
      Cessation of Operation. Somraj Saha may at any time, in its sole
      discretion and without advance notice to you, cease operation of the
      Website and distribution of the Products.
    </p>
    <p>
      Entire Agreement. This Agreement comprises the entire agreement between
      you and Somraj Saha and supersedes any prior agreements pertaining to the
      subject matter contained herein.
    </p>
    <p>
      Effect of Waiver. The failure of Somraj Saha to exercise or enforce any
      right or provision of this Agreement will not constitute a waiver of such
      right or provision. If any provision of this Agreement is found by a court
      of competent jurisdiction to be invalid, the parties nevertheless agree
      that the court should endeavor to give effect to the parties&apos;
      intentions as reflected in the provision, and the other provisions of this
      Agreement remain in full force and effect.
    </p>
    <p>
      Governing Law;
      <a href="https://main.sci.gov.in/jurisdiction" target="_blank">
        Supreme Court of India
      </a>
      . This Website originates from the city of Agartala in Tripura, India.
      This Agreement will be governed by the laws of the State of India without
      regard to its conflict of law principles to the contrary. Neither you nor
      Somraj Saha will commence or prosecute any suit, proceeding or claim to
      enforce the provisions of this Agreement, to recover damages for breach of
      or default of this Agreement, or otherwise arising under or by reason of
      this Agreement, other than in courts located in State of India. By using
      this Website or ordering and/or subscribing to our Products, you consent
      to the jurisdiction and venue of such courts in connection with any
      action, suit, proceeding or claim arising under or by reason of this
      Agreement. You hereby waive any right to trial by jury arising out of this
      Agreement and any related documents.
    </p>
    <p>
      Statute of Limitation. You agree that regardless of any statute or law to
      the contrary, any claim or cause of action arising out of or related to
      use of the Website or Products or this Agreement must be filed within one
      (1) year after such claim or cause of action arose or be forever barred.
    </p>
    <p>
      Waiver of Class Action Rights. BY ENTERING INTO THIS AGREEMENT, YOU HEREBY
      IRREVOCABLY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH THOSE OF
      OTHER IN THE FORM OF A CLASS ACTION OR SIMILAR PROCEDURAL DEVICE. ANY
      CLAIMS ARISING OUT OF, RELATING TO, OR CONNECTION WITH THIS AGREEMENT MUST
      BE ASSERTED INDIVIDUALLY.
    </p>
    <p>
      Termination. Somraj Saha reserves the right to terminate your access to
      the Website if it reasonably believes, in its sole discretion, that you
      have breached any of the terms and conditions of this Agreement. Following
      termination, you will not be permitted to use the Website and Somraj Saha
      may, in its sole discretion and without advance notice to you, cancel any
      outstanding orders for Products. If your access to the Website is
      terminated, Somraj Saha reserves the right to exercise whatever means it
      deems necessary to prevent unauthorized access of the Website. This
      Agreement will survive indefinitely unless and until Somraj Saha chooses,
      in its sole discretion and without advance to you, to terminate it.
    </p>
    <p>
      Domestic Use. Somraj Saha makes no representation that the Website or
      Products are appropriate or available for use in locations outside India.
      Users who access the Website from outside India do so at their own risk
      and initiative and must bear all responsibility for compliance with any
      applicable local laws.
    </p>
    <p>
      Assignment. You may not assign your rights and obligations under this
      Agreement to anyone. Somraj Saha may assign its rights and obligations
      under this Agreement in its sole discretion and without advance notice to
      you.
    </p>
    <p>
      BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO
      BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
    </p>
  </article>
</template>

<script lang="ts" setup>
const title = "Terms and Conditions";
const description = `Read the Terms and Conditions for using jarmos.dev, including
product usage, services, privacy, intellectual property, and legal disclaimers.`;
const baseURL = useRuntimeConfig().public.baseURL;
const image = "/icons/favicon.svg";

// Set the title of the page
useHead({
  title: title,
});

// Set the SEO metadata for the page.
useSeoMeta({
  description: description,
  ogTitle: title,
  ogDescription: description,
  ogImage: image,
  ogUrl: `${baseURL}/terms-and-conditions`,
  twitterTitle: title,
  twitterDescription: description,
  twitterImage: image,
  twitterCard: "summary",
});
</script>

<style lang="scss" scoped>
article {
  padding: 0 2rem;
  margin: 2rem auto;

  // Tablet
  @media screen and (min-width: 768px) {
    padding: 0 4rem;
  }

  // Laptops
  @media screen and (min-width: 1024px) {
    padding: 0 7rem;
  }

  // 2K Desktops
  @media screen and (min-width: 1440px) {
    padding: 0 14rem;
  }
}
</style>
