// src/components/layout/navbar.tsx
"use client";

import { useEffect, useState } from "react";

import Image from "next/image";
import Link from "next/link";

import { GiHamburgerMenu } from "react-icons/gi";
import { IoMdClose } from "react-icons/io";

import { navlinks } from "@constants/navlinks";

function MobileMenu() {
  return (
    <div className="bg-blue-30 p-4 text-center text-lg font-bold md:hidden">
      <ul className="flex-col space-y-2">
        {navlinks.map((link) => (
          <li
            key={link.label}
            className="text-black-100 rounded-sm bg-green-10 py-2"
          >
            <Link href={link.href} className="underline underline-offset-2">
              {link.label}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

// TODO: Refactor the navbar to be stick & open the menu on top of other content
// See this documentation on Flowbite for more information:
// https://flowbite.com/docs/components/navbar/#sticky-navbar
function Navbar() {
  // State handler for toggling the mobile menu open/close
  const [isMenuOpen, setMenuOpen] = useState<boolean>(false);

  // Side-effect to close the mobile menu when navigating to another page
  useEffect(() => {
    setMenuOpen(false);
  }, []);

  return (
    <>
      <nav
        className="container mx-auto flex max-w-screen-sm items-center
        justify-between px-4 pt-4 sm:px-0 lg:max-w-screen-md
        xl:max-w-screen-lg 2xl:max-w-screen-xl"
      >
        <Link
          href="/"
          className="rounded-lg focus:outline-none focus:ring-2
          focus:ring-white-30"
        >
          <Image
            src="/assets/logo-og.svg"
            alt="Website logo"
            width={70}
            height={70}
          />
        </Link>

        <button
          type="button"
          aria-controls="navbar-hamburger"
          aria-expanded="false"
          className="sm:hidden md:rounded-lg md:p-2 md:hover:bg-blue-40
          md:focus:outline-none md:focus:ring-2 md:focus:ring-white-30"
          onClick={() => setMenuOpen(!isMenuOpen)}
        >
          <span className="sr-only">Open Main Menu</span>
          {isMenuOpen ? (
            <IoMdClose size={22} color="#ECF8FF" />
          ) : (
            <GiHamburgerMenu size={22} color="#ECF8FF" />
          )}
        </button>

        <span className="hidden md:flex md:space-x-8">
          {navlinks.map((link) => (
            <Link
              key={link.label}
              href={link.href}
              className="text-white-10 underline-offset-4 hover:text-green-30
              hover:underline"
            >
              {link.label}
            </Link>
          ))}
        </span>
      </nav>

      {isMenuOpen ? <MobileMenu /> : ""}
    </>
  );
}

export default Navbar;

// website/components/common/NavBar.vue
<template>
  <nav>
    <!-- Website logo -->
    <div class="logo">
      <img src="/icons/logo.svg" alt="logo" width="50" height="50" >
      <span v-if="!isMobile">jarmos.dev</span>
    </div>

    <!-- Hamburger menu icon (displayed ONLY on mobile viewports) -->
    <div v-if="isMobile" @click="toggle()">
      <img src="/icons/menu.svg" alt="menu" width="40" height="40" >
    </div>

    <!-- Navigation links (displayed ONLY on large screens) -->
    <div v-else class="nav-links">
      <ul>
        <li v-for="(link, index) in props.navLinks" :key="index">
          <CommonNavLink :href="link.href">
            {{ link.label }}
          </CommonNavLink>
        </li>
      </ul>
    </div>
  </nav>

  <Teleport to="body">
    <CommonMobileMenu
      v-if="isOpen"
      :nav-links="props.navLinks"
      @close-menu="toggle()"
    />
  </Teleport>
</template>

<script lang="ts" setup>
import type { NavBarProps } from "~/types/components/NavBar";

// Define the props to pass to the component
const props = defineProps<NavBarProps>();

// Check whether the viewport is mobile
const { isMobile } = useIsMobile();

// Fetch the toggle state and the toggle function to switch the button close/open
const { state: isOpen, toggle } = useToggle();
</script>

<style lang="scss" scoped>
nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem 2rem;
  position: sticky;
  top: 0;
  background-color: #111a20;

  // Tablet
  @media screen and (min-width: 768px) {
    padding: 1.5rem 4rem;
  }

  // Laptops
  @media screen and (min-width: 1024px) {
    padding: 1.5rem 7rem;
  }

  // 2K laptops
  @media screen and (min-width: 1440px) {
    padding: 1.5rem 14rem;
  }

  .logo {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 1.5rem;
    font-weight: bolder;
  }

  .nav-links {
    ul {
      display: flex;
      gap: 1.5rem;
      list-style-type: none;
    }
  }
}
</style>
